dist: xenial

sudo: required

language: python

python:
  - "3.7"
#  - "3.8-dev"  # 3.8 development branch
#  - "nightly"  # nightly build

install:
  - python --versio
  - pwd
  - mkdir -p ~/.cloudmesh
  - wget -P ~/.cloudmesh https://raw.githubusercontent.com/cloudmesh/cloudmesh-cloud/master/cloudmesh/etc/cloudmesh4.yaml
  - wget -P ~/.cloudmesh https://raw.githubusercontent.com/cloudmesh/cloudmesh-common/master/cloudmesh/etc/cloudmesh.yaml
  - ls .cloudmesh
  - pip install cloudmesh-installer
  - pip install cloudmesh-common
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install .
  - ls
  - pwd

script: pytest -v tests/test_bookmanager.py
