dist: xenial

sudo: required

language: python

python:
  - "3.7"
#  - "3.8-dev"  # 3.8 development branch
#  - "nightly"  # nightly build

install:
  - sudo apt-get install tree
  - wget -q https://github.com/jgm/pandoc/releases/download/2.7.2/pandoc-2.7.2-1-amd64.deb
  - sudo dpkg -i pandoc-2.7.2-1-amd64.deb
  - pandoc --version
  - python --version
  - pwd
  - mkdir -p ~/.cloudmesh
  - wget -P ~/.cloudmesh https://raw.githubusercontent.com/cloudmesh/cloudmesh-cloud/master/cloudmesh/etc/cloudmesh4.yaml
  - wget -P ~/.cloudmesh https://raw.githubusercontent.com/cloudmesh/cloudmesh-common/master/cloudmesh/etc/cloudmesh.yaml
  - ls ~/.cloudmesh
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install .
  - tree .
  - pwd

script: pytest -v --capture=no tests/test_bookmanager.py
